//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
  destinations: Destinations;
  destinationsConnection: DestinationsConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  testimonials: Testimonials;
  testimonialsConnection: TestimonialsConnection;
  team: Team;
  teamConnection: TeamConnection;
  socialFeed: SocialFeed;
  socialFeedConnection: SocialFeedConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryDestinationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDestinationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DestinationsFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryTestimonialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QuerySocialFeedArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySocialFeedConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SocialFeedFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  settings?: InputMaybe<SettingsFilter>;
  destinations?: InputMaybe<DestinationsFilter>;
  services?: InputMaybe<ServicesFilter>;
  testimonials?: InputMaybe<TestimonialsFilter>;
  team?: InputMaybe<TeamFilter>;
  socialFeed?: InputMaybe<SocialFeedFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Settings | Destinations | Services | Testimonials | Team | SocialFeed | Folder;

export type Home = Node & Document & {
  __typename?: 'Home';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  goldWord?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  mapImageUrl?: Maybe<Scalars['String']['output']>;
  secondaryCta?: Maybe<Scalars['String']['output']>;
  secondaryCtaLink?: Maybe<Scalars['String']['output']>;
  primaryCta?: Maybe<Scalars['String']['output']>;
  primaryCtaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  goldWord?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  mapImageUrl?: InputMaybe<ImageFilter>;
  secondaryCta?: InputMaybe<StringFilter>;
  secondaryCtaLink?: InputMaybe<StringFilter>;
  primaryCta?: InputMaybe<StringFilter>;
  primaryCtaLink?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type SettingsContact = {
  __typename?: 'SettingsContact';
  phones?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  email?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  contact?: Maybe<SettingsContact>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SettingsContactFilter = {
  phones?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  contact?: InputMaybe<SettingsContactFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type DestinationsDestinationsGallery = {
  __typename?: 'DestinationsDestinationsGallery';
  url?: Maybe<Scalars['String']['output']>;
};

export type DestinationsDestinationsFaqs = {
  __typename?: 'DestinationsDestinationsFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type DestinationsDestinations = {
  __typename?: 'DestinationsDestinations';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  region?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<DestinationsDestinationsGallery>>>;
  duration?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  highlights?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  itinerary?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  faqs?: Maybe<Array<Maybe<DestinationsDestinationsFaqs>>>;
};

export type Destinations = Node & Document & {
  __typename?: 'Destinations';
  destinations?: Maybe<Array<Maybe<DestinationsDestinations>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DestinationsDestinationsGalleryFilter = {
  url?: InputMaybe<ImageFilter>;
};

export type DestinationsDestinationsFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type DestinationsDestinationsFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  region?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  gallery?: InputMaybe<DestinationsDestinationsGalleryFilter>;
  duration?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  highlights?: InputMaybe<StringFilter>;
  itinerary?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<DestinationsDestinationsFaqsFilter>;
};

export type DestinationsFilter = {
  destinations?: InputMaybe<DestinationsDestinationsFilter>;
};

export type DestinationsConnectionEdges = {
  __typename?: 'DestinationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Destinations>;
};

export type DestinationsConnection = Connection & {
  __typename?: 'DestinationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DestinationsConnectionEdges>>>;
};

export type ServicesServices = {
  __typename?: 'ServicesServices';
  title: Scalars['String']['output'];
  navTitle?: Maybe<Scalars['String']['output']>;
  slug: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  highlights?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  services?: Maybe<Array<Maybe<ServicesServices>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesServicesFilter = {
  title?: InputMaybe<StringFilter>;
  navTitle?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  highlights?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  services?: InputMaybe<ServicesServicesFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type TestimonialsReviews = {
  __typename?: 'TestimonialsReviews';
  name?: Maybe<Scalars['String']['output']>;
  trip?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
};

export type Testimonials = Node & Document & {
  __typename?: 'Testimonials';
  reviews?: Maybe<Array<Maybe<TestimonialsReviews>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialsReviewsFilter = {
  name?: InputMaybe<StringFilter>;
  trip?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type TestimonialsFilter = {
  reviews?: InputMaybe<TestimonialsReviewsFilter>;
};

export type TestimonialsConnectionEdges = {
  __typename?: 'TestimonialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonials>;
};

export type TestimonialsConnection = Connection & {
  __typename?: 'TestimonialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialsConnectionEdges>>>;
};

export type TeamTeam = {
  __typename?: 'TeamTeam';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  team?: Maybe<Array<Maybe<TeamTeam>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamTeamFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type TeamFilter = {
  team?: InputMaybe<TeamTeamFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type SocialFeedInstagramFeed = {
  __typename?: 'SocialFeedInstagramFeed';
  caption?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type SocialFeed = Node & Document & {
  __typename?: 'SocialFeed';
  instagramFeed?: Maybe<Array<Maybe<SocialFeedInstagramFeed>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SocialFeedInstagramFeedFilter = {
  caption?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type SocialFeedFilter = {
  instagramFeed?: InputMaybe<SocialFeedInstagramFeedFilter>;
};

export type SocialFeedConnectionEdges = {
  __typename?: 'SocialFeedConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SocialFeed>;
};

export type SocialFeedConnection = Connection & {
  __typename?: 'SocialFeedConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SocialFeedConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateSettings: Settings;
  createSettings: Settings;
  updateDestinations: Destinations;
  createDestinations: Destinations;
  updateServices: Services;
  createServices: Services;
  updateTestimonials: Testimonials;
  createTestimonials: Testimonials;
  updateTeam: Team;
  createTeam: Team;
  updateSocialFeed: SocialFeed;
  createSocialFeed: SocialFeed;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateDestinationsArgs = {
  relativePath: Scalars['String']['input'];
  params: DestinationsMutation;
};


export type MutationCreateDestinationsArgs = {
  relativePath: Scalars['String']['input'];
  params: DestinationsMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationCreateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateSocialFeedArgs = {
  relativePath: Scalars['String']['input'];
  params: SocialFeedMutation;
};


export type MutationCreateSocialFeedArgs = {
  relativePath: Scalars['String']['input'];
  params: SocialFeedMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  settings?: InputMaybe<SettingsMutation>;
  destinations?: InputMaybe<DestinationsMutation>;
  services?: InputMaybe<ServicesMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  team?: InputMaybe<TeamMutation>;
  socialFeed?: InputMaybe<SocialFeedMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  settings?: InputMaybe<SettingsMutation>;
  destinations?: InputMaybe<DestinationsMutation>;
  services?: InputMaybe<ServicesMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  team?: InputMaybe<TeamMutation>;
  socialFeed?: InputMaybe<SocialFeedMutation>;
};

export type HomeMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  goldWord?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  mapImageUrl?: InputMaybe<Scalars['String']['input']>;
  secondaryCta?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaLink?: InputMaybe<Scalars['String']['input']>;
  primaryCta?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLink?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsContactMutation = {
  phones?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  email?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  contact?: InputMaybe<SettingsContactMutation>;
};

export type DestinationsDestinationsGalleryMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
};

export type DestinationsDestinationsFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type DestinationsDestinationsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<DestinationsDestinationsGalleryMutation>>>;
  duration?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  highlights?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  itinerary?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  faqs?: InputMaybe<Array<InputMaybe<DestinationsDestinationsFaqsMutation>>>;
};

export type DestinationsMutation = {
  destinations?: InputMaybe<Array<InputMaybe<DestinationsDestinationsMutation>>>;
};

export type ServicesServicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  navTitle?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  highlights?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesMutation = {
  services?: InputMaybe<Array<InputMaybe<ServicesServicesMutation>>>;
};

export type TestimonialsReviewsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  trip?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialsMutation = {
  reviews?: InputMaybe<Array<InputMaybe<TestimonialsReviewsMutation>>>;
};

export type TeamTeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  team?: InputMaybe<Array<InputMaybe<TeamTeamMutation>>>;
};

export type SocialFeedInstagramFeedMutation = {
  caption?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type SocialFeedMutation = {
  instagramFeed?: InputMaybe<Array<InputMaybe<SocialFeedInstagramFeedMutation>>>;
};

export type HomePartsFragment = { __typename: 'Home', eyebrow?: string | null, title?: string | null, goldWord?: string | null, subtitle?: string | null, mapImageUrl?: string | null, secondaryCta?: string | null, secondaryCtaLink?: string | null, primaryCta?: string | null, primaryCtaLink?: string | null };

export type SettingsPartsFragment = { __typename: 'Settings', contact?: { __typename: 'SettingsContact', phones?: Array<string | null> | null, email?: string | null, hours?: string | null, address?: string | null, whatsapp?: string | null } | null };

export type DestinationsPartsFragment = { __typename: 'Destinations', destinations?: Array<{ __typename: 'DestinationsDestinations', title: string, slug: string, region?: string | null, summary?: string | null, image?: string | null, duration?: string | null, price?: string | null, highlights?: Array<string | null> | null, itinerary?: Array<string | null> | null, gallery?: Array<{ __typename: 'DestinationsDestinationsGallery', url?: string | null } | null> | null, faqs?: Array<{ __typename: 'DestinationsDestinationsFaqs', question?: string | null, answer?: string | null } | null> | null } | null> | null };

export type ServicesPartsFragment = { __typename: 'Services', services?: Array<{ __typename: 'ServicesServices', title: string, navTitle?: string | null, slug: string, summary?: string | null, heroImage?: string | null, highlights?: Array<string | null> | null } | null> | null };

export type TestimonialsPartsFragment = { __typename: 'Testimonials', reviews?: Array<{ __typename: 'TestimonialsReviews', name?: string | null, trip?: string | null, quote?: string | null } | null> | null };

export type TeamPartsFragment = { __typename: 'Team', team?: Array<{ __typename: 'TeamTeam', name?: string | null, role?: string | null, image?: string | null } | null> | null };

export type SocialFeedPartsFragment = { __typename: 'SocialFeed', instagramFeed?: Array<{ __typename: 'SocialFeedInstagramFeed', caption?: string | null, href?: string | null, image?: string | null } | null> | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, eyebrow?: string | null, title?: string | null, goldWord?: string | null, subtitle?: string | null, mapImageUrl?: string | null, secondaryCta?: string | null, secondaryCtaLink?: string | null, primaryCta?: string | null, primaryCtaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, eyebrow?: string | null, title?: string | null, goldWord?: string | null, subtitle?: string | null, mapImageUrl?: string | null, secondaryCta?: string | null, secondaryCtaLink?: string | null, primaryCta?: string | null, primaryCtaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contact?: { __typename: 'SettingsContact', phones?: Array<string | null> | null, email?: string | null, hours?: string | null, address?: string | null, whatsapp?: string | null } | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contact?: { __typename: 'SettingsContact', phones?: Array<string | null> | null, email?: string | null, hours?: string | null, address?: string | null, whatsapp?: string | null } | null } | null } | null> | null } };

export type DestinationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DestinationsQuery = { __typename?: 'Query', destinations: { __typename: 'Destinations', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, destinations?: Array<{ __typename: 'DestinationsDestinations', title: string, slug: string, region?: string | null, summary?: string | null, image?: string | null, duration?: string | null, price?: string | null, highlights?: Array<string | null> | null, itinerary?: Array<string | null> | null, gallery?: Array<{ __typename: 'DestinationsDestinationsGallery', url?: string | null } | null> | null, faqs?: Array<{ __typename: 'DestinationsDestinationsFaqs', question?: string | null, answer?: string | null } | null> | null } | null> | null } };

export type DestinationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DestinationsFilter>;
}>;


export type DestinationsConnectionQuery = { __typename?: 'Query', destinationsConnection: { __typename?: 'DestinationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DestinationsConnectionEdges', cursor: string, node?: { __typename: 'Destinations', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, destinations?: Array<{ __typename: 'DestinationsDestinations', title: string, slug: string, region?: string | null, summary?: string | null, image?: string | null, duration?: string | null, price?: string | null, highlights?: Array<string | null> | null, itinerary?: Array<string | null> | null, gallery?: Array<{ __typename: 'DestinationsDestinationsGallery', url?: string | null } | null> | null, faqs?: Array<{ __typename: 'DestinationsDestinationsFaqs', question?: string | null, answer?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'ServicesServices', title: string, navTitle?: string | null, slug: string, summary?: string | null, heroImage?: string | null, highlights?: Array<string | null> | null } | null> | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'ServicesServices', title: string, navTitle?: string | null, slug: string, summary?: string | null, heroImage?: string | null, highlights?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type TestimonialsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialsQuery = { __typename?: 'Query', testimonials: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, reviews?: Array<{ __typename: 'TestimonialsReviews', name?: string | null, trip?: string | null, quote?: string | null } | null> | null } };

export type TestimonialsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
}>;


export type TestimonialsConnectionQuery = { __typename?: 'Query', testimonialsConnection: { __typename?: 'TestimonialsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialsConnectionEdges', cursor: string, node?: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, reviews?: Array<{ __typename: 'TestimonialsReviews', name?: string | null, trip?: string | null, quote?: string | null } | null> | null } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, team?: Array<{ __typename: 'TeamTeam', name?: string | null, role?: string | null, image?: string | null } | null> | null } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, team?: Array<{ __typename: 'TeamTeam', name?: string | null, role?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export type SocialFeedQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SocialFeedQuery = { __typename?: 'Query', socialFeed: { __typename: 'SocialFeed', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, instagramFeed?: Array<{ __typename: 'SocialFeedInstagramFeed', caption?: string | null, href?: string | null, image?: string | null } | null> | null } };

export type SocialFeedConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SocialFeedFilter>;
}>;


export type SocialFeedConnectionQuery = { __typename?: 'Query', socialFeedConnection: { __typename?: 'SocialFeedConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SocialFeedConnectionEdges', cursor: string, node?: { __typename: 'SocialFeed', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, instagramFeed?: Array<{ __typename: 'SocialFeedInstagramFeed', caption?: string | null, href?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  eyebrow
  title
  goldWord
  subtitle
  mapImageUrl
  secondaryCta
  secondaryCtaLink
  primaryCta
  primaryCtaLink
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  contact {
    __typename
    phones
    email
    hours
    address
    whatsapp
  }
}
    `;
export const DestinationsPartsFragmentDoc = gql`
    fragment DestinationsParts on Destinations {
  __typename
  destinations {
    __typename
    title
    slug
    region
    summary
    image
    gallery {
      __typename
      url
    }
    duration
    price
    highlights
    itinerary
    faqs {
      __typename
      question
      answer
    }
  }
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  services {
    __typename
    title
    navTitle
    slug
    summary
    heroImage
    highlights
  }
}
    `;
export const TestimonialsPartsFragmentDoc = gql`
    fragment TestimonialsParts on Testimonials {
  __typename
  reviews {
    __typename
    name
    trip
    quote
  }
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  team {
    __typename
    name
    role
    image
  }
}
    `;
export const SocialFeedPartsFragmentDoc = gql`
    fragment SocialFeedParts on SocialFeed {
  __typename
  instagramFeed {
    __typename
    caption
    href
    image
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const DestinationsDocument = gql`
    query destinations($relativePath: String!) {
  destinations(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DestinationsParts
  }
}
    ${DestinationsPartsFragmentDoc}`;
export const DestinationsConnectionDocument = gql`
    query destinationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DestinationsFilter) {
  destinationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DestinationsParts
      }
    }
  }
}
    ${DestinationsPartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const TestimonialsDocument = gql`
    query testimonials($relativePath: String!) {
  testimonials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialsParts
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const TestimonialsConnectionDocument = gql`
    query testimonialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialsFilter) {
  testimonialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialsParts
      }
    }
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const SocialFeedDocument = gql`
    query socialFeed($relativePath: String!) {
  socialFeed(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SocialFeedParts
  }
}
    ${SocialFeedPartsFragmentDoc}`;
export const SocialFeedConnectionDocument = gql`
    query socialFeedConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SocialFeedFilter) {
  socialFeedConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SocialFeedParts
      }
    }
  }
}
    ${SocialFeedPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    destinations(variables: DestinationsQueryVariables, options?: C): Promise<{data: DestinationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsQueryVariables, query: string}> {
        return requester<{data: DestinationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsQueryVariables, query: string}, DestinationsQueryVariables>(DestinationsDocument, variables, options);
      },
    destinationsConnection(variables?: DestinationsConnectionQueryVariables, options?: C): Promise<{data: DestinationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsConnectionQueryVariables, query: string}> {
        return requester<{data: DestinationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsConnectionQueryVariables, query: string}, DestinationsConnectionQueryVariables>(DestinationsConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    testimonials(variables: TestimonialsQueryVariables, options?: C): Promise<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}> {
        return requester<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}, TestimonialsQueryVariables>(TestimonialsDocument, variables, options);
      },
    testimonialsConnection(variables?: TestimonialsConnectionQueryVariables, options?: C): Promise<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}, TestimonialsConnectionQueryVariables>(TestimonialsConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    socialFeed(variables: SocialFeedQueryVariables, options?: C): Promise<{data: SocialFeedQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SocialFeedQueryVariables, query: string}> {
        return requester<{data: SocialFeedQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SocialFeedQueryVariables, query: string}, SocialFeedQueryVariables>(SocialFeedDocument, variables, options);
      },
    socialFeedConnection(variables?: SocialFeedConnectionQueryVariables, options?: C): Promise<{data: SocialFeedConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SocialFeedConnectionQueryVariables, query: string}> {
        return requester<{data: SocialFeedConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SocialFeedConnectionQueryVariables, query: string}, SocialFeedConnectionQueryVariables>(SocialFeedConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  